apiVersion: v1
kind: Service
metadata:
  name: reddit-classifier-service
spec:
  selector:
    app: reddit-classifier
  type: LoadBalancer  # Already LoadBalancer in your original
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8000  # Container port
      # Remove nodePort if it exists